#!/bin/bash
#
#                                                                   __                               
#                                                                  / _|                              
#                                                                 | |_ __ _ _ __ _ __ ___   ___ _ __ 
#                                                                 |  _/ _` | '__| '_ ` _ \ / _ \ '__|
#                                                                 | || (_| | |  | | | | | |  __/ |   
#                                                                 |_| \__,_|_|  |_| |_| |_|\___|_|   
#                                                                                                    
#									By Manikumar Juttukonda                                                                        
#
#
pid=$$
whereami=`pwd`
home=${whereami}
cd ${home}; stat canal fruits soils seeds &>/dev/null; if [ $? -ne 0 ]; then echo "Error: Required directories(canal, fruits, soils, seeds) are missing. Please make sure to clone most latest source"; exit 1; fi
umask 0027
seconds=0
canal_dir="${home}/canal";
fruits_dir="${home}/fruits";
soils_dir="${home}/soils";
seeds="${home}/seeds";

